version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3

    # working_directory: ~/static_web

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - persist_to_workspace:
          root: .
          paths:
            - .
      # - run:
      #     name: s3 deploy
      #     command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/. s3://my-hosted-conten --exclude ".git/*" --region us-east-1            


  deploy:
    # working_directory: ~/static_web
    docker:
      - image: circleci/python:3.6.3
    steps:
      - attach_workspace:
          at: .
      - checkout 
      - run:
          name: Deploy
          command: |
              aws s3 sync . s3://my-hosted-conten --delete --exact-timestamps;               
      # - run:
      #     name: s3 deploy
      #     command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/. s3://my-hosted-conten --exclude ".git/*" --region us-east-1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
