version: 2.1
jobs:
  build:
    machine:
       image: ubuntu-2004:202010-01

    # working_directory: ~/static_web

    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
             sudo apt-get update
             sudo apt install python3-pip
             sudo pip3 install awsebcli --upgrade
      # - run:
      #     name: Install AWS CLI
      #     command: pip install awscli --upgrade --user
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      # - run:
      #     name: s3 deploy
      #     command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/. s3://my-hosted-conten --exclude ".git/*" --region us-east-1            


  deploy:
    # working_directory: ~/static_web
    machine:
       image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout 
      - run:
          name: Deploy
          command: |
              aws s3 sync ./ s3://my-hosted-conten --delete --exact-timestamps \
              --exclude ".git/*" \
              --exclude ".circleci/*";               
      # - run:
      #     name: s3 deploy
      #     command: ~/.local/bin/aws s3 sync --delete --acl public-read ~/. s3://my-hosted-conten --exclude ".git/*" --region us-east-1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
